#include "Config.hpp"

#include <cstdlib>
#include <iostream>

namespace cg {

[[noreturn]] void help_and_exit() {
    std::cout
        << "Usage: cg_md [options]\n"
        << "\nCore:\n"
        << "  --project-dir PATH              --dry-run                     --run-tag NAME\n"
        << "  --stage all|cg|prepare|relax|em|nvt|npt|production|adaptive|metadynamics|pmf\n"
        << "          |fes|center|report|contact-map\n"
        << "  --gmx CMD                       --martinize CMD              --insane CMD\n"
        << "  --packmol CMD                   --plumed CMD                 --mpirun CMD\n"
        << "  --python CMD\n"
        << "  --modify RESNAME-RESID          --merge-chains A,B            --dssp\n"
        << "\nRelaxed starting structure (inserted between coarse-graining and packing):\n"
        << "  --relax                         --relax-us US                 --relax-frames N\n"
        << "  --relax-cluster-cutoff-nm NM    --relax-discard-frac F\n"
        << "  --distinct-copies               (one relaxation frame per copy; needs --relax)\n"
        << "\nSystem:\n"
        << "  --n-prot N                      --protomer NAME\n"
        << "  --seq-length N                  --atoms-per-prot N            --phospho\n"
        << "  --ss-string STRING              --temperature-K T             --salt-M M\n"
        << "  --ntomp N                       --seed N\n"
        << "  --pin auto|on|off               --pinoffset N                 --pinstride N\n"
        << "\nMartinize2 extra force-field/mapping (required for --phospho, e.g. SEP/TPO/PTR):\n"
        << "  --martinize-ff-dir PATH         --martinize-map-dir PATH\n"
        << "\nPreparation:\n"
        << "  --no-elastic                    --elastic-units A:B\n"
        << "  --packmol-box-A A               --packmol-cluster-radius-A A\n"
        << "  --packmol-tolerance-A A         --packmol-radius-A A\n"
        << "  --solvation-mode gromacs|insane --box-type TYPE               --box-margin-nm NM\n"
        << "  --solvate-radius-nm NM          --martini-water-gro PATH      --no-ions\n"
        << "  --martini-lambda-pw X           (protein-water rescaling; 1.0 = stock Martini 3)\n"
        << "\nSimulation:\n"
        << "  --nvt-dt-ps PS                  --nvt-nsteps N\n"
        << "  --npt-dt-ps PS                  --npt-nsteps N\n"
        << "  --md-dt-ps PS                   --md-total-us US\n"
        << "  --plumed-stride N               --contact-r0-nm NM\n"
        << "  --contact-nn N                  --contact-mm N\n"
        << "  --epsilon-r X (Martini: 15)     --rcoulomb-nm NM              --rvdw-nm NM\n"
        << "  --nstlist N                     --rlist-nm NM\n"
        << "  --verlet-buffer-tolerance X     (-1 = fixed rlist, Martini's choice; 0.005 lets\n"
        << "                                   mdrun size the buffer and raise nstlist on GPU)\n"
        << "  --nst-xtc N                     --nst-energy N                --nst-log N\n"
        << "  --xtc-precision N               (1/nm; Martini uses 100, GROMACS defaults to 1000)\n"
        << "  --thermostat system|protein-solvent|legacy\n"
        << "\nMetadynamics:\n"
        << "  --metadynamics                  --metad-walkers N             --metad-model PATH\n"
        << "  --metad-cv-params PATH          --metad-sigma CSV\n"
        << "  --metad-nodes N                 --metad-pace N\n"
        << "  --metad-height X                --metad-biasfactor X          --metad-print-stride N\n"
        << "  --metad-total-us US             --metad-chunk-us US\n"
        << "  --metad-feature-cols CSV        --metad-grid-min CSV          --metad-grid-max CSV\n"
        << "  --metad-grid-bin N              --metad-grid-wstride N        --metad-rct-ustride N\n"
        << "  --metad-fes-stride N            --no-metad-grid               --no-metad-rct\n"
        << "  --no-metad-work                 --no-metad-sum-hills          --no-metad-center\n"
        << "  --metad-wall-kt X               --metad-wall-margin-frac F\n"
        << "\nDimerization PMF (two chains, well-tempered metadynamics on d_1_2):\n"
        << "  --pmf                           --pmf-wall-nm NM              --pmf-wall-kappa X\n"
        << "  --pmf-sigma-nm NM               --pmf-bound-cutoff-nm NM      --pmf-plateau-frac F\n"
        << "  (reuses --metad-height/-pace/-biasfactor/-walkers/-chunk-us/-total-us)\n"
        << "\nReporting:\n"
        << "  --report-script PATH            --no-report\n"
        << "  --contact-map-cutoff-nm NM      --contact-map-stride N\n"
        << "\nAdaptive:\n"
        << "  --adaptive                      --adaptive-chunk-us US         --adaptive-max-total-us US\n"
        << "  --adaptive-min-total-us US      --adaptive-min-cn-transitions N\n"
        << "  --adaptive-min-bidirectional-events N\n"
        << "  --adaptive-min-cn-range X       --adaptive-min-rg-range X\n"
        << "  --adaptive-min-contact-patterns N --adaptive-min-lcc-unique N\n"
        << "  --adaptive-pair-contact-threshold X --adaptive-smooth-window N\n"
        << "  --adaptive-min-residence N      --adaptive-pattern-downsample N\n"
        << "  --adaptive-max-pattern-growth X --adaptive-max-pattern-jsd X   (bits; two halves agree)\n"
        << "  --adaptive-min-effective-samples N   (block-averaging plateau of cn_total)\n"
        << "  --adaptive-min-assembly-events N     --adaptive-event-residence-ps PS\n"
        << "  --adaptive-min-time-over-its X       (run length / slowest implied timescale; 0 = off)\n"
        << "\nOutput:\n"
        << "  --keep-intermediate-trajectories   (keep md_all.xtc / md_all_whole.xtc)\n";
    std::exit(0);
}

} // namespace cg
