#include "PlumedWriter.hpp"
#include "Config.hpp"
#include "FileUtils.hpp"
#include "StringUtils.hpp"

#include <set>
#include <sstream>
#include <stdexcept>
#include <utility>
namespace cg {
namespace {

bool parse_all_doubles(const std::vector<std::string>& items, std::vector<double>& out) {
    out.clear();
    out.reserve(items.size());
    for (const auto& item : items) {
        try {
            std::size_t used = 0;
            const double value = std::stod(item, &used);
            if (trim(item.substr(used)).empty()) { out.push_back(value); continue; }
        } catch (const std::exception&) {  }
        return false;
    }
    return true;
}
} // namespace

PlumedFiles write_metad_plumed_dat(const Config& cfg,
                                   const std::filesystem::path& plumed_path,
                                   const std::filesystem::path& ndx_path,
                                   const std::filesystem::path& model_path,
                                   const std::filesystem::path& colvar_path,
                                   const MetadPlumedOptions& options) {
    const auto d = build_descriptors(cfg, ndx_path);

    const auto sorted = build_sorted_descriptors(d);
    const bool invariant = cfg.metad_permutation_invariant && !cfg.pmf;

    auto model_args = cfg.metad_feature_cols.empty()
                          ? (invariant ? sorted.feature_cols : d.feature_cols)
                          : split_csv(cfg.metad_feature_cols);
    if (model_args.empty()) throw std::runtime_error("Metadynamics CV has an empty feature list.");

    std::set<std::string> defined(d.feature_cols.begin(), d.feature_cols.end());
    if (invariant) defined.insert(sorted.feature_cols.begin(), sorted.feature_cols.end());
    for (const auto& arg : model_args) {
        if (defined.count(arg)) continue;
        throw std::runtime_error(
            "Trained CV expects feature '" + arg + "', which this plumed.dat does not define. "
            "The CV was trained on a COLVAR produced by a different --n-prot / descriptor set than the "
            "one being biased. Re-train the CV against this system's COLVAR (cg_cvgen), or pass the "
            "matching --metad-feature-cols. Available: " + join(d.feature_cols, ","));
    }

    std::ostringstream p;
    if (options.restart) {
        p << "# Continuation batch: re-read HILLS and resume the accumulated bias.\n"
          << "RESTART\n\n";
    }

    p << "# Metadynamics descriptors for " << cfg.systemName()
      << " - generated by the same builder as the unbiased production input,\n"
      << "# so the CV sees byte-for-byte the same definitions it was trained on.\n"
      << "UNITS LENGTH=nm TIME=ps\n\n"
      << d.text << '\n';

    std::vector<std::string> nodes;
    if (cfg.pmf) {
        nodes.push_back(d.distances.front());
        p << "# Dimerization PMF: biasing the inter-chain COM distance directly.\n"
          << "# The wall confines the pair to a finite sampling volume, which is what\n"
          << "# makes the unbound state - and therefore a standard-state correction -\n"
          << "# well defined. It must sit beyond the interaction range AND inside half\n"
          << "# the box vector, or the plateau is corrupted by periodic images.\n"
          << "wall: UPPER_WALLS ARG=" << nodes.front()
          << " AT=" << to_string_fixed(cfg.pmf_wall_nm, 4)
          << " KAPPA=" << to_string_fixed(cfg.pmf_wall_kappa, 1)
          << " EXP=2 OFFSET=0\n\n";
    } else {
        if (invariant) p << sorted.text << '\n';
        p << "mycv: PYTORCH_MODEL FILE=" << model_path.string()
          << " ARG=" << join(model_args, ",") << "\n\n";
        nodes.reserve(static_cast<std::size_t>(cfg.metad_nodes));
        for (int i = 0; i < cfg.metad_nodes; ++i) nodes.push_back("mycv.node-" + std::to_string(i));
    }

    const bool grid = cfg.metad_grid && !cfg.metad_grid_min.empty() && !cfg.metad_grid_max.empty();

    bool walls = false;
    if (grid && !cfg.pmf && cfg.metad_wall_kt > 0.0) {
        std::vector<double> gmin, gmax;
        const bool numeric = parse_all_doubles(split_csv(cfg.metad_grid_min), gmin) &&
                             parse_all_doubles(split_csv(cfg.metad_grid_max), gmax);
        if (numeric && gmin.size() == nodes.size() && gmax.size() == nodes.size()) {
            const double kT = 0.0083144621 * cfg.temperature_K;
            std::vector<std::string> lower_at, upper_at, kappa;
            bool ok = true;
            for (std::size_t i = 0; i < nodes.size(); ++i) {
                const double lo = gmin[i], hi = gmax[i];
                const double inset = cfg.metad_wall_margin_frac * (hi - lo);
                if (!(inset > 0.0)) { ok = false; break; }
                lower_at.push_back(to_string_fixed(lo + inset, 4));
                upper_at.push_back(to_string_fixed(hi - inset, 4));
                kappa.push_back(to_string_fixed(cfg.metad_wall_kt * kT / (inset * inset), 4));
            }
            if (ok) {
                walls = true;
                p << "# Grid walls: PLUMED aborts if a biased CV leaves GRID_MIN/GRID_MAX, so the\n"
                     "# CV is restrained " << to_string_fixed(100.0 * cfg.metad_wall_margin_frac, 1)
                  << "% of the grid span inside each bound. KAPPA is set so that\n"
                     "# reaching the bound itself would cost " << to_string_fixed(cfg.metad_wall_kt, 1)
                  << " kT, i.e. the bound is unreachable.\n"
                  << "lwall: LOWER_WALLS ARG=" << join(nodes, ",") << " AT=" << join(lower_at, ",")
                  << " KAPPA=" << join(kappa, ",") << " EXP=2 OFFSET=0\n"
                  << "uwall: UPPER_WALLS ARG=" << join(nodes, ",") << " AT=" << join(upper_at, ",")
                  << " KAPPA=" << join(kappa, ",") << " EXP=2 OFFSET=0\n\n";
            }
        }
    }

    p << "metad: METAD ...\n"
      << "ARG=" << join(nodes, ",") << "\n"
      << "PACE=" << cfg.metad_pace << "\n"
      << "HEIGHT=" << cfg.metad_height << "\n"
      << "SIGMA=" << cfg.metad_sigma << "\n"
      << "BIASFACTOR=" << cfg.metad_biasfactor << "\n"
      << "TEMP=" << cfg.temperature_K << "\n"
      << "FILE=" << options.hills_file << "\n";

    if (grid) {
        p << "GRID_MIN=" << cfg.metad_grid_min << "\n"
          << "GRID_MAX=" << cfg.metad_grid_max << "\n"
          << "GRID_BIN=" << repeat_csv(std::to_string(cfg.metad_grid_bin), nodes.size()) << "\n";
        if (cfg.metad_calc_rct) {
            p << "CALC_RCT\n"
              << "RCT_USTRIDE=" << cfg.metad_rct_ustride << "\n";
        }
        if (cfg.metad_grid_wstride > 0)
            p << "GRID_WFILE=" << cfg.metad_grid_file << "\n"
              << "GRID_WSTRIDE=" << cfg.metad_grid_wstride << "\n";
    }

    if (grid && cfg.metad_calc_work) p << "CALC_WORK\n";
    if (cfg.metad_walkers > 1) p << "WALKERS_MPI\n";
    p << "...\n\n";

    auto print_args = nodes;
    if (cfg.pmf) print_args.push_back("wall.bias");
    if (walls) print_args.insert(print_args.end(), {"lwall.bias", "uwall.bias"});
    print_args.push_back("metad.bias");
    if (grid && cfg.metad_calc_rct) print_args.insert(print_args.end(), {"metad.rbias", "metad.rct"});
    if (grid && cfg.metad_calc_work) print_args.push_back("metad.work");
    p << "PRINT STRIDE=" << cfg.metad_print_stride
      << " ARG=" << join(print_args, ",")
      << " FILE=" << colvar_path.string() << '\n';

    const auto monitor_path = colvar_path.parent_path() / cfg.metad_monitor_file;
    auto monitor_args = d.feature_cols;
    if (grid && cfg.metad_calc_rct) monitor_args.push_back("metad.rbias");
    p << "\nPRINT STRIDE=" << cfg.plumed_stride << " FILE=" << monitor_path.string()
      << " ARG=" << join(monitor_args, ",") << '\n';

    if (!cfg.dry_run) write_text(plumed_path, p.str());
    return {plumed_path, {}, model_args};
}

} // namespace cg
